# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8000:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/teamc/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
    image: jenkins/ssh-agent:jdk17
    privileged: true
    user: root
    container_name: agent
    volumes:
      - /home/teamc/settings.xml:/home/jenkins/.m2/settings.xml
    expose:
      - 22
    environment:
      - GIT_AUTH= "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"
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPRYQAUSCXfhW8dD1OxjnLZqEKI/NajerfSt2oD9/g05 teamc@vmpx18
